name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight
  workflow_dispatch:       # Allows manual run
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman
        uses: liununu/github-activity-pacman@main
        with:
          user_name: Mido-77
          output_name: pacman.svg

      - name: Setup output directory
        run: |
          mkdir -p dist
          mv pacman.svg dist/

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
