name: Multiple Animations

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # Snake
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Mido-77
          outputs: dist/github-contribution-grid-snake.svg
          
      # 3D Chart
      - name: Generate 3D Chart
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: Mido-77
          
      # Tetris
      - name: Generate Tetris
        uses: denvercoder1/github-readme-tetris-stats@main
        with:
          github_user_name: Mido-77
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
